FROM payara/server-full:5.191

COPY /ClickDigitalBackend_war_exploded /opt/payara/deployments/ClickDigitalBackend_war_exploded
COPY /hosts /opt/payara/appserver/glassfish/domains/production/config/
COPY /credentials /opt/payara/appserver/glassfish/domains/production/config/

